// Generated by https://quicktype.io

export interface IPokeResponse {
  count: number;
  next: string;
  previous: null;
  results: IPokemon[];
}

export interface IPokemon {
  name: string;
  url: string;
}
